# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire',             '~> 4.7.3'
  pod 'ObjectMapper',          '~> 3.3.0'
  pod 'AlamofireObjectMapper', '~> 5.1.0'

end
